Improvements
autodatadirect/use-manifest pull request #2
Opened 2020-01-09 18:31 UTC by mrprim

Added hooks for Column and Cell definitions.  Added loading logic.

2020-01-09 19:13 UTC, frodare requested changes

2020-01-09 19:13 UTC, frodare commented on src/components/ButtonPager/index.js
> +  const numberedPageButtons = pagerLogic.determinePages(page, pageSize, count)
this logic should be moved into `usePager`

2020-01-09 19:13 UTC, frodare commented on src/components/ButtonPager/index.js
> +import PagerButton from '../PagerButton'
I think PageButton should be moved into this component folder

2020-01-09 19:13 UTC, frodare commented on src/components/DefaultManifestTable/index.js
> +  const { definition, rows, loadingData } = useManifest()
we should consider having three loading flags, `loading`, `loadingData` (or maybe `loadingPage`), and `loadingCount`. were loading = loadingPage && loadingCount.  And `loading` should be used in this component

2020-01-09 19:13 UTC, frodare commented on src/components/Table/index.js
> +const Table = ({ className, columnCount, rowCount }) =>
I would like to see all code dealing with the HTML table in this component. I think we should dissolve the Headers and Rows component into here and this component handle the entire scaffolding of the manifest.

2020-01-09 19:13 UTC, frodare commented on src/components/PageSizer/index.js
>    return (
I think we should remove all of the bootstrap classes

2020-01-09 19:13 UTC, frodare commented on src/hooks/usePager.js
> +  const { state, dispatch } = useContext(manifestContext)
I think we should only use `useContext` inside of `useManifest`

2020-01-09 19:13 UTC, frodare commented on src/utils/reducer.js
>  export const initialState = {
after looking over this reducer, I think it should be replaced with some `useState` hooks.  There isn't any complex side effects from setting data, it looks like simple persistence.

2020-01-09 19:13 UTC, frodare commented on src/utils/createSequentialIntegerArray.js
> +export default length => Array(length).fill().map((_, i) => i)
I have to say, with a name that like, ... I expected more.

2020-01-09 19:13 UTC, frodare commented on src/hooks/usePager.js
> +  const { page, pageSize, count } = state
after switching to useManifest, we shouldn't need all of these double unpacking lines

2020-01-10 18:49 UTC, frodare commented on src/hooks/usePager.js
> +  const pages = pagerLogic.determinePages(numberOfPages, page, pageSize, count)
we should probably take this in as an object so that the arguments are named

2020-01-10 19:21 UTC, frodare approved these changes

2020-01-10 20:01 UTC, zeriley approved these changes

2020-01-10 20:11 UTC, merged